name: CFRM541_QRM
channels:
  - conda-forge
dependencies:
  - jupyter 
  - matplotlib >= 3.8
  - pandas >= 2.0
  - pandas-datareader
  - pip >= 24.0
  - python = 3.12
  - scikit-learn >= 1.4
  - arch >= 5.0
  - pip:
      - plotly == 5.24.0
      - seaborn == 0.13.2
      - pywin32
      - openpyxl
      - xlwings