name: CFRM541_QRM
channels:
  - conda-forge
dependencies:
  - jupyter 
  - matplotlib
  - pandas
  - scikit-learn
  - pip:
      - plotly == 5.24.0
      - seaborn == 0.13.2
      - pywin32
      - openpyxl
      - xlwings
  # Also need to install manaully:
  # -arch
  